plugins { id 'com.android.application' }

android {
    namespace 'com.vands.vmixcontroller'
    compileSdk 35

    defaultConfig {
        applicationId "com.vands.vmixcontroller"
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName "2.1-fullscreen"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            minifyEnabled false
        }
    }
}
